version: '3.8'
services:
  client:
    build: ./backend
    environment:
      - REDIS_HOST=cache
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./backend/index.js:/app/index.js
    depends_on:
      - cache
  cache:
    image: bitnami/redis:6.0.16
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./cache/redis.conf:/opt/bitnami/redis/mounted-etc/overrides.conf
    ports:
      - "6379:6379"

