version: '3.8'
services:
  client:
    build: ./client
    environment:
      - PORT=3001
      - BACKEND_PORT=3000
      - BACKEND_HOST=backend
    ports:
      - 3001:3001
    volumes:
      - ./client/client.js:/app/client.js
    depends_on:
      - backend    
  backend:
    build: ./backend
    environment:
      - REDIS_HOST=cache
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./backend/backend.js:/app/backend.js
    depends_on:
      - cache
  cache:
    image: bitnami/redis:6.0.16
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./cache/redis.conf:/opt/bitnami/redis/mounted-etc/overrides.conf
    ports:
      - "6379:6379"
